#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f {{ source_file() }} --list

# ***************************************
# build
# ***************************************

build:  
  #!/usr/bin/env bash
  set -eufo pipefail

  docker build -f Dockerfile.osv -t renovate_examples_osv:latest . 
  docker build -f Dockerfile.ubuntu -t renovate_examples_ubuntu:latest . 

# ***************************************
# test
# ***************************************

test:  
  #!/usr/bin/env bash
  set -eufo pipefail

  echo "Skipping tests"