set dotenv-load := true

export DEFAULT_APPLICATION:="uv"

# default lists actions
default:
  @just -f justfile --list

clean:
  rm -rf ./.terraform_state || true

install:
  #!/usr/bin/env bash
  set -eufo pipefail
  tfenv use
  terraform init

lint:
  #!/usr/bin/env bash
  set -eufo pipefail
  tfenv use
  terraform fmt

test: install
  #!/usr/bin/env bash
  set -eufo pipefail
  tfenv use
  #terraform plan

build: install
  #!/usr/bin/env bash
  set -eufo pipefail
  tfenv use
  terraform plan